apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: {{ .Values.namespace }}
data:
  nginx.conf: |
    server {
        listen 80;
        root /usr/share/nginx/html/labtop;
    }
