{{ if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
  generation: 1
  labels:
    k8s-app: labtop-info
  name: labtop-info
  namespace: {{ .Values.namespace }}
spec:
  rules:
  - host: labtop-info.127.0.0.1.nip.io
    http:
      paths:
      - backend:
          service:
            name: labtop-info
            port:
              name: http
        path: /
        pathType: Prefix
{{ end }}
